//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int Cust_Id { get; set; }
        public string COMPANYCODE { get; set; }
        public string CUSTOMER { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CUSTOMERGRP { get; set; }
        public string SEARCHTERM { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string POSTALCODE { get; set; }
        public string REGION { get; set; }
        public string EMAILADDR { get; set; }
        public string PHONENO { get; set; }
        public string FAXNO { get; set; }
        public string PAYMENTTERMS { get; set; }
        public string TEXT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public string ECCNO { get; set; }
        public string CSTNO { get; set; }
        public string LSTNO { get; set; }
        public string PANNO { get; set; }
        public string SERVICETAXREGNNO { get; set; }
        public string MARKETINGGROUP { get; set; }
        public string KEYMANAGER { get; set; }
        public string AGENT { get; set; }
        public string TARGET { get; set; }
        public string EMPLOYEE { get; set; }
        public Nullable<int> Cust_Code { get; set; }
    }
}
