//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferMaster
    {
        public int Id { get; set; }
        public string Dv { get; set; }
        public string SaTy { get; set; }
        public string Sold_to_pt { get; set; }
        public string Name_1 { get; set; }
        public string Purchase_order_number { get; set; }
        public string Document { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public string Material { get; set; }
        public string Material_Description { get; set; }
        public string Exch_Rate { get; set; }
        public string Curr { get; set; }
        public string ConfirmQty { get; set; }
        public string Net_value1 { get; set; }
        public string Net_price { get; set; }
        public string Net_Value { get; set; }
        public string Prb { get; set; }
        public Nullable<System.DateTime> Dlv_Date { get; set; }
        public string Prod_hier { get; set; }
        public string Prod_Description { get; set; }
        public string CGrp { get; set; }
        public string Key_Managr { get; set; }
        public string SDst { get; set; }
        public string Customer_Z { get; set; }
        public string Vendor_Name { get; set; }
        public string Matl_Group { get; set; }
        public string Mat_Grp_Descr { get; set; }
        public string Cust_Ind_C { get; set; }
        public string Cust_Ind_D { get; set; }
        public string OrdRs { get; set; }
    }
}
