//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int ID { get; set; }
        public string Match { get; set; }
        public string MRP_Controller { get; set; }
        public string Dv { get; set; }
        public string SaTy { get; set; }
        public string Sales_Doc { get; set; }
        public string Item { get; set; }
        public string Sch_Line { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public string Sold_to_party { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public string Order_Qty { get; set; }
        public string Open_Qty { get; set; }
        public string Unit_Basic_Price { get; set; }
        public string Curr { get; set; }
        public string Total_Price_IRS { get; set; }
        public string Purchase_order_no { get; set; }
        public Nullable<System.DateTime> PO_date { get; set; }
        public string Usage { get; set; }
        public string Old_material_no { get; set; }
        public string Sold_to_pt { get; set; }
        public Nullable<System.DateTime> Req_dlv_dt { get; set; }
        public string Customer_group_1 { get; set; }
        public string Product_hierarchy { get; set; }
        public string Exchange_Rate { get; set; }
        public string IncoT { get; set; }
        public string Inco_2 { get; set; }
        public string Payment_terms { get; set; }
        public string Filter { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
        public string Week_Required { get; set; }
        public string Required_Year { get; set; }
        public string Production_Week { get; set; }
        public string Production_Year { get; set; }
        public string Week_Scheduled { get; set; }
        public string Week_Changed { get; set; }
        public string Remarks_from_Production { get; set; }
        public string Remarks_from_Marketing { get; set; }
        public string Logistics_Remarks { get; set; }
        public string Adv_Received { get; set; }
        public string Marketing_Sales_Week { get; set; }
        public string Credit_In_Week { get; set; }
        public string Payment_Collection_Week { get; set; }
        public string For_new_SO_entry_in_Remarks_Sheet { get; set; }
        public string Pre_Dispatch_Inspection { get; set; }
        public string Approved_Transporter { get; set; }
        public string PI_Payment { get; set; }
        public string Tax_amount { get; set; }
        public string Grp2 { get; set; }
        public string Grp3 { get; set; }
        public string Grp4 { get; set; }
        public string MG1 { get; set; }
        public string Product_hierarchy1 { get; set; }
        public string Material_group_1 { get; set; }
        public string Product_hierarchy2 { get; set; }
        public string Your_Ref { get; set; }
        public string MG2 { get; set; }
        public string Material_group_2 { get; set; }
        public string Grp5 { get; set; }
        public string Customer_group_5 { get; set; }
        public string ConvFactor { get; set; }
        public string Mat_Group { get; set; }
    }
}
