//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending_invoice_Master
    {
        public int Id { get; set; }
        public string CoCd { get; set; }
        public string Customer { get; set; }
        public string Assignment { get; set; }
        public string Year { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> Pstng_Date { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public string Reference { get; set; }
        public string Doc_Type { get; set; }
        public string Period { get; set; }
        public string D_C { get; set; }
        public string Amount_in_LC { get; set; }
        public string Amount_in_LC1 { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Bline_Date { get; set; }
        public string PayT { get; set; }
        public string Sales_Doc { get; set; }
        public string Item { get; set; }
        public string Payment_reference { get; set; }
        public string Group { get; set; }
        public string Plan_group { get; set; }
        public string G_L_Acct { get; set; }
        public string Customer_Number_1 { get; set; }
        public string Document_Type { get; set; }
        public string Debit_Credit_Indicator { get; set; }
        public string Itm { get; set; }
        public string Recon_acct { get; set; }
        public string Group1 { get; set; }
        public string Cl { get; set; }
        public string Customer_classification { get; set; }
        public string Customer_Account_Group { get; set; }
        public string Pers_No { get; set; }
        public string Planning_group { get; set; }
        public string Last_name_First_name { get; set; }
        public string Crcy { get; set; }
        public string Amount { get; set; }
        public string Amount1 { get; set; }
        public string Day1 { get; set; }
        public string Disc1 { get; set; }
    }
}
