//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class admin_vulcan2devEntities : DbContext
    {
        public admin_vulcan2devEntities()
            : base("name=admin_vulcan2devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<UserInRoleMaster> UserInRoleMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserPasswordHistory> UserPasswordHistories { get; set; }
        public virtual DbSet<UserInKeyManagerMaster> UserInKeyManagerMasters { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<OfferMaster> OfferMasters { get; set; }
        public virtual DbSet<Pending_invoice_Master> Pending_invoice_Master { get; set; }
        public virtual DbSet<Summary_Master> Summary_Master { get; set; }
        public virtual DbSet<OrderMaster> OrderMasters { get; set; }
        public virtual DbSet<KeyManagerMaster> KeyManagerMasters { get; set; }
    
        public virtual ObjectResult<GetClientwiseSummaryData_Result> GetClientwiseSummaryData(Nullable<int> userId, Nullable<System.DateTime> fyStart, Nullable<System.DateTime> fyend, string kAMId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var fyStartParameter = fyStart.HasValue ?
                new ObjectParameter("fyStart", fyStart) :
                new ObjectParameter("fyStart", typeof(System.DateTime));
    
            var fyendParameter = fyend.HasValue ?
                new ObjectParameter("fyend", fyend) :
                new ObjectParameter("fyend", typeof(System.DateTime));
    
            var kAMIdParameter = kAMId != null ?
                new ObjectParameter("KAMId", kAMId) :
                new ObjectParameter("KAMId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClientwiseSummaryData_Result>("GetClientwiseSummaryData", userIdParameter, fyStartParameter, fyendParameter, kAMIdParameter);
        }
    
        public virtual ObjectResult<GetSummaryData_Result> GetSummaryData(Nullable<int> userId, Nullable<System.DateTime> fyStart, Nullable<System.DateTime> fyend)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var fyStartParameter = fyStart.HasValue ?
                new ObjectParameter("fyStart", fyStart) :
                new ObjectParameter("fyStart", typeof(System.DateTime));
    
            var fyendParameter = fyend.HasValue ?
                new ObjectParameter("fyend", fyend) :
                new ObjectParameter("fyend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSummaryData_Result>("GetSummaryData", userIdParameter, fyStartParameter, fyendParameter);
        }
    }
}
